import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeBase from './home'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Front End test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <HomeBase />

      
    </div>
  )
}
